"""
Fetch external pet-health datasets from HuggingFace and merge them with
the existing local dataset into an augmented training file.

Datasets pulled
---------------
1. Local base dataset               — your existing merged_pet_dataset.parquet
2. infinite-dataset-hub/VetPetCare  — free, no account needed, 90 rows
   covers cardiovascular, blood disorders, genitourinary
3. data/synthetic_data.parquet      — generated by generate_synthetic.py using
   your Gemini API key (free, 100+ examples per weak class)
4. SAVSNET/PetEVAL                  — gated, 17,600 professional EHRs
   Requires HF account + accepted conditions + HF_TOKEN env var

Recommended free pipeline (no HF account needed)
-------------------------------------------------
# Step 1 — generate synthetic data for weak classes using your Gemini key:
python -m app.ml.generate_synthetic

# Step 2 — merge everything:
python -m app.ml.fetch_and_merge

# Step 3 — retrain with Bio_ClinicalBERT (free, no account needed):
python -m app.ml.train \\
    --data-path data/merged_augmented.parquet \\
    --label-map data/label_map.json \\
    --model-dir models/transformer_model \\
    --base-model emilyalsentzer/Bio_ClinicalBERT \\
    --epochs 8 --batch-size 16 --lr 2e-5

With PetEVAL (gated — needs HF_TOKEN):
---------------------------------------
HF_TOKEN=hf_xxxx python -m app.ml.fetch_and_merge
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import pandas as pd


# ---------------------------------------------------------------------------
# Label map helpers
# ---------------------------------------------------------------------------

SKIP_SENTINEL = "__SKIP__"

# VetPetCare diagnoses that are procedures / symptoms / too vague to classify
_VETPETCARE_SKIP = {
    "anticonvulsant therapy",
    "behavioral conditioning",
    "dehydration",
    "dental caries",
    "diet change",
    "health risk",
    "idiopathic",
    "insulin therapy",
    "iodine-131 therapy",
    "knee surgery",
    "liver support",
    "quarantine and antibiotics",
    "supportive care with diet and hydration",
    "tail docking and pain management",
    "tooth extraction",
}

# PetEVAL Presenting Complaint labels to skip (non-condition buckets)
_PETEVALSKIP_COMPLAINTS = {
    "Post-operative",
    "Vaccination",
    "Other Healthy",
    "Other Unwell",
}


def _load_label_map(path: str) -> dict[str, str]:
    with open(path, encoding="utf-8") as f:
        raw = json.load(f)
    return {k: str(v) for k, v in raw.items() if not k.startswith("//") and v}


def _apply_label_map(label: str, label_map: dict[str, str]) -> str | None:
    """Return mapped label, None to skip row, or original label if not in map."""
    if label in _VETPETCARE_SKIP:
        return None
    mapped = label_map.get(label, label)
    return mapped if mapped != SKIP_SENTINEL else None


# ---------------------------------------------------------------------------
# Source loaders — each returns a DataFrame with columns: text, condition, record_type
# ---------------------------------------------------------------------------

def _load_local(data_path: str) -> pd.DataFrame:
    path = Path(data_path)
    if not path.exists():
        print(f"  [skip] Local file not found: {path}")
        return pd.DataFrame()
    suffix = path.suffix.lower()
    df = pd.read_csv(path) if suffix == ".csv" else pd.read_parquet(path)
    print(f"  Loaded {len(df)} rows from {path.name}")
    return df[["text", "condition", "record_type"]].copy()


def _load_vetpetcare(label_map: dict[str, str]) -> pd.DataFrame:
    """
    infinite-dataset-hub/VetPetCare — 90 rows.
    Constructs rich text from symptoms + species + breed + age.
    """
    from datasets import load_dataset

    ds = load_dataset("infinite-dataset-hub/VetPetCare", split="train")
    raw = ds.to_pandas()

    rows = []
    for _, r in raw.iterrows():
        diagnosis = str(r.get("diagnosis", "")).strip().lower()
        if not diagnosis:
            continue

        mapped = _apply_label_map(diagnosis, label_map)
        if mapped is None:
            continue

        species = str(r.get("species", "Pet")).strip()
        breed = str(r.get("breed", "")).strip()
        age = r.get("age", "")
        symptoms = str(r.get("symptoms", "")).strip()
        treatment = str(r.get("treatment_plan", "")).strip()

        # Build a richer symptom sentence so the model has more signal
        parts = [f"A {species.lower()}"]
        if breed and breed.lower() not in ("none", "nan"):
            parts[0] += f" ({breed})"
        if age and str(age) not in ("nan", "0"):
            parts[0] += f", {age} years old"
        parts.append(f"presents with: {symptoms}.")
        if treatment and treatment.lower() not in ("none", "nan"):
            parts.append(f"Treatment: {treatment}.")
        text = " ".join(parts)

        rows.append({"text": text, "condition": mapped, "record_type": "VetPetCare"})

    df = pd.DataFrame(rows)
    print(f"  Loaded {len(df)} usable rows from VetPetCare")
    return df


def _load_petevalopen() -> pd.DataFrame:
    """
    SAVSNET/PetEVAL — gated dataset, 17,600 professional EHRs.
    Requires HF_TOKEN env var and accepted dataset conditions at:
    https://huggingface.co/datasets/SAVSNET/PetEVAL
    Returns empty DataFrame if token missing or access denied.
    """
    hf_token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_TOKEN")
    if not hf_token:
        print("  [skip] PetEVAL: HF_TOKEN not set. To enable, set HF_TOKEN=hf_xxxx")
        print("         Accept dataset conditions at: https://huggingface.co/datasets/SAVSNET/PetEVAL")
        return pd.DataFrame()

    try:
        from datasets import load_dataset

        ds = load_dataset("SAVSNET/PetEVAL", token=hf_token)
        splits = list(ds.keys())
        print(f"  PetEVAL splits: {splits}")

        frames = []
        for split in splits:
            df_split = ds[split].to_pandas()
            frames.append(df_split)
        raw = pd.concat(frames, ignore_index=True)

        print(f"  PetEVAL columns: {list(raw.columns)}")
        print(f"  PetEVAL total rows: {len(raw)}")

        # Detect text column
        text_col = None
        for candidate in ["text", "clinical_notes", "narrative", "consultation_text", "note"]:
            if candidate in raw.columns:
                text_col = candidate
                break

        # Detect label column (Main Presenting Complaint preferred)
        label_col = None
        for candidate in ["main_presenting_complaint", "mpc", "presenting_complaint",
                          "syndromic_label", "label", "condition", "icd_label"]:
            if candidate in raw.columns:
                label_col = candidate
                break

        if text_col is None or label_col is None:
            print(f"  [skip] PetEVAL: couldn't find text/label columns in {list(raw.columns)}")
            return pd.DataFrame()

        rows = []
        for _, r in raw.iterrows():
            label = str(r[label_col]).strip()
            if label in _PETEVALSKIP_COMPLAINTS or not label:
                continue
            text = str(r[text_col]).strip()
            if len(text) < 10:
                continue

            # Map PetEVAL labels via label_map.json (Gastrointestinal → Digestive Issues etc.)
            # If not in map, keep as-is and let train.py's min-samples filter handle it
            rows.append({"text": text, "condition": label, "record_type": "PetEVAL"})

        df = pd.DataFrame(rows)
        print(f"  Loaded {len(df)} usable rows from PetEVAL")
        return df

    except Exception as exc:
        print(f"  [skip] PetEVAL failed to load: {exc}")
        return pd.DataFrame()


# ---------------------------------------------------------------------------
# Main merge logic
# ---------------------------------------------------------------------------

def _load_synthetic(synthetic_path: str) -> pd.DataFrame:
    """Load pre-generated synthetic data from generate_synthetic.py."""
    path = Path(synthetic_path)
    if not path.exists():
        print(f"  [skip] Synthetic data not found: {path}")
        print("         Run first: python -m app.ml.generate_synthetic")
        return pd.DataFrame()
    suffix = path.suffix.lower()
    df = pd.read_csv(path) if suffix == ".csv" else pd.read_parquet(path)
    print(f"  Loaded {len(df)} synthetic rows from {path.name}")
    return df[["text", "condition", "record_type"]].copy()


def fetch_and_merge(
    local_path: str = "data/merged_pet_dataset.parquet",
    synthetic_path: str = "data/synthetic_data.parquet",
    label_map_path: str = "data/label_map.json",
    output_path: str = "data/merged_augmented.parquet",
    skip_vetpetcare: bool = False,
    skip_synthetic: bool = False,
    skip_petevalopen: bool = False,
    min_text_length: int = 15,
) -> None:
    label_map = _load_label_map(label_map_path)
    frames: list[pd.DataFrame] = []

    # 1. Existing local dataset
    print("\n[1/4] Loading local dataset...")
    local_df = _load_local(local_path)
    if not local_df.empty:
        local_df["condition"] = local_df["condition"].map(
            lambda c: label_map.get(str(c).strip(), str(c).strip())
        )
        frames.append(local_df)

    # 2. VetPetCare (free, no account needed)
    if not skip_vetpetcare:
        print("\n[2/4] Fetching VetPetCare (free)...")
        try:
            vetpetcare_df = _load_vetpetcare(label_map)
            if not vetpetcare_df.empty:
                frames.append(vetpetcare_df)
        except ImportError:
            print("  [skip] VetPetCare: install 'datasets' package first")
        except Exception as exc:
            print(f"  [skip] VetPetCare failed: {exc}")
    else:
        print("\n[2/4] VetPetCare: skipped (--skip-vetpetcare)")

    # 3. Synthetic data from Gemini (free — uses your existing API key)
    if not skip_synthetic:
        print("\n[3/4] Loading synthetic data (Gemini-generated)...")
        synthetic_df = _load_synthetic(synthetic_path)
        if not synthetic_df.empty:
            frames.append(synthetic_df)
    else:
        print("\n[3/4] Synthetic data: skipped (--skip-synthetic)")

    # 4. PetEVAL (gated — optional)
    if not skip_petevalopen:
        print("\n[4/4] Fetching PetEVAL (gated — needs HF_TOKEN)...")
        try:
            petevalopen_df = _load_petevalopen()
            if not petevalopen_df.empty:
                petevalopen_df["condition"] = petevalopen_df["condition"].map(
                    lambda c: label_map.get(str(c).strip(), str(c).strip())
                )
                frames.append(petevalopen_df)
        except ImportError:
            print("  [skip] PetEVAL: install 'datasets' package first")
    else:
        print("\n[4/4] PetEVAL: skipped (--skip-petevalopen)")

    if not frames:
        raise RuntimeError("No data loaded — nothing to merge.")

    # Merge + clean
    merged = pd.concat(frames, ignore_index=True)
    merged["text"] = merged["text"].astype(str).str.replace(r"\s+", " ", regex=True).str.strip()
    merged["condition"] = merged["condition"].astype(str).str.strip()
    merged = merged[merged["text"].str.len() >= min_text_length]
    merged = merged.dropna(subset=["text", "condition"])
    merged = merged[merged["condition"] != "nan"]
    merged["record_type"] = merged["record_type"].fillna("External Dataset")

    # Deduplicate on text+condition
    before = len(merged)
    merged = merged.drop_duplicates(subset=["text", "condition"])
    print(f"\nDeduplication removed {before - len(merged)} rows")

    # Summary
    print(f"\n{'='*50}")
    print(f"Final merged dataset: {len(merged)} rows, {merged['condition'].nunique()} classes")
    print("\nClass distribution:")
    print(merged["condition"].value_counts().to_string())
    print(f"\nSource breakdown:")
    print(merged["record_type"].value_counts().to_string())

    # Save
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    merged.to_parquet(output, index=False)
    print(f"\nSaved to: {output}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch external vet datasets and merge into augmented training file.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--local-path", default="data/merged_pet_dataset.parquet",
                        help="Existing local dataset to include.")
    parser.add_argument("--synthetic-path", default="data/synthetic_data.parquet",
                        help="Synthetic data file from generate_synthetic.py.")
    parser.add_argument("--label-map", default="data/label_map.json",
                        help="Label consolidation map JSON.")
    parser.add_argument("--output", default="data/merged_augmented.parquet",
                        help="Output path for the augmented dataset.")
    parser.add_argument("--skip-vetpetcare", action="store_true",
                        help="Skip fetching VetPetCare.")
    parser.add_argument("--skip-synthetic", action="store_true",
                        help="Skip loading synthetic data.")
    parser.add_argument("--skip-petevalopen", action="store_true",
                        help="Skip fetching PetEVAL (gated).")
    parser.add_argument("--min-text-length", type=int, default=15,
                        help="Drop rows with text shorter than this.")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    fetch_and_merge(
        local_path=args.local_path,
        synthetic_path=args.synthetic_path,
        label_map_path=args.label_map,
        output_path=args.output,
        skip_vetpetcare=args.skip_vetpetcare,
        skip_synthetic=args.skip_synthetic,
        skip_petevalopen=args.skip_petevalopen,
        min_text_length=args.min_text_length,
    )
