"""
Fetch external pet-health datasets from HuggingFace and merge them with
the existing local dataset into an augmented training file.

Datasets pulled
---------------
1. Local base dataset               — your existing merged_pet_dataset.parquet
2. infinite-dataset-hub/VetPetCare  — free, no account needed, 90 rows
   covers cardiovascular, blood disorders, genitourinary
3. data/synthetic_data.parquet      — generated by generate_synthetic.py using
   your Gemini API key (free, 100+ examples per weak class)
4. SAVSNET/PetEVAL                  — gated, 17,600 professional EHRs
   Requires HF account + accepted conditions + HF_TOKEN env var

Recommended free pipeline (no HF account needed)
-------------------------------------------------
# Step 1 — generate synthetic data for weak classes using your Gemini key:
python -m ml_pipeline.generate_synthetic

# Step 2 — merge everything:
python -m ml_pipeline.fetch_and_merge

# Step 3 — retrain with Bio_ClinicalBERT (free, no account needed):
python -m ml_pipeline.train \\
    --data-path data/merged_augmented.parquet \\
    --label-map data/label_map.json \\
    --model-dir models/transformer_model \\
    --base-model emilyalsentzer/Bio_ClinicalBERT \\
    --epochs 8 --batch-size 16 --lr 2e-5

With PetEVAL (gated — needs HF_TOKEN):
---------------------------------------
HF_TOKEN=hf_xxxx python -m ml_pipeline.fetch_and_merge
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

from ml_pipeline.dataset_sources import DatasetSourceError, SourceMode, SourceResult, load_source

# ---------------------------------------------------------------------------
# Label map helpers
# ---------------------------------------------------------------------------

SKIP_SENTINEL = "__SKIP__"

# VetPetCare diagnoses that are procedures / symptoms / too vague to classify
_VETPETCARE_SKIP = {
    "anticonvulsant therapy",
    "behavioral conditioning",
    "dehydration",
    "dental caries",
    "diet change",
    "health risk",
    "idiopathic",
    "insulin therapy",
    "iodine-131 therapy",
    "knee surgery",
    "liver support",
    "quarantine and antibiotics",
    "supportive care with diet and hydration",
    "tail docking and pain management",
    "tooth extraction",
}

# PetEVAL Presenting Complaint labels to skip (non-condition buckets)
_PETEVALSKIP_COMPLAINTS = {
    "Post-operative",
    "Vaccination",
    "Other Healthy",
    "Other Unwell",
}


def _load_label_map(path: str) -> dict[str, str]:
    with open(path, encoding="utf-8") as f:
        raw = json.load(f)
    return {k: str(v) for k, v in raw.items() if not k.startswith("//") and v}


def _apply_label_map(label: str, label_map: dict[str, str]) -> str | None:
    """Return mapped label, None to skip row, or original label if not in map."""
    if label in _VETPETCARE_SKIP:
        return None
    mapped = label_map.get(label, label)
    return mapped if mapped != SKIP_SENTINEL else None


# ---------------------------------------------------------------------------
# Source loaders — each returns a DataFrame with columns: text, condition, record_type
# ---------------------------------------------------------------------------


def _load_local(data_path: str) -> pd.DataFrame:
    path = Path(data_path)
    if not path.exists():
        print(f"  [skip] Local file not found: {path}")
        return pd.DataFrame()
    suffix = path.suffix.lower()
    df = pd.read_csv(path) if suffix == ".csv" else pd.read_parquet(path)
    print(f"  Loaded {len(df)} rows from {path.name}")
    return df[["text", "condition", "record_type"]].copy()


def _load_vetpetcare(label_map: dict[str, str], revision: str | None = None) -> pd.DataFrame:
    """
    infinite-dataset-hub/VetPetCare — 90 rows.
    Constructs rich text from symptoms + species + breed + age.

    `revision` pins the exact HF dataset snapshot used for this build so it
    can be recorded in the build manifest — an unpinned load can silently
    change contents between runs (see "Canonical and traceable dataset
    builds" in specs/reproducible-ml-lifecycle/spec.md).
    """
    from datasets import load_dataset

    ds = load_dataset("infinite-dataset-hub/VetPetCare", split="train", revision=revision)
    raw = ds.to_pandas()

    rows = []
    for _, r in raw.iterrows():
        diagnosis = str(r.get("diagnosis", "")).strip().lower()
        if not diagnosis:
            continue

        mapped = _apply_label_map(diagnosis, label_map)
        if mapped is None:
            continue

        species = str(r.get("species", "Pet")).strip()
        breed = str(r.get("breed", "")).strip()
        age = r.get("age", "")
        symptoms = str(r.get("symptoms", "")).strip()
        treatment = str(r.get("treatment_plan", "")).strip()

        # Build a richer symptom sentence so the model has more signal
        parts = [f"A {species.lower()}"]
        if breed and breed.lower() not in ("none", "nan"):
            parts[0] += f" ({breed})"
        if age and str(age) not in ("nan", "0"):
            parts[0] += f", {age} years old"
        parts.append(f"presents with: {symptoms}.")
        if treatment and treatment.lower() not in ("none", "nan"):
            parts.append(f"Treatment: {treatment}.")
        text = " ".join(parts)

        rows.append({"text": text, "condition": mapped, "record_type": "VetPetCare"})

    df = pd.DataFrame(rows)
    print(f"  Loaded {len(df)} usable rows from VetPetCare")
    return df


def _load_petevalopen(revision: str | None = None) -> pd.DataFrame:
    """
    SAVSNET/PetEVAL — gated dataset, 17,600 professional EHRs.
    Requires HF_TOKEN env var and accepted dataset conditions at:
    https://huggingface.co/datasets/SAVSNET/PetEVAL
    Returns empty DataFrame if token missing or access denied.

    `revision` pins the exact HF dataset snapshot — see `_load_vetpetcare`.
    """
    hf_token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_TOKEN")
    if not hf_token:
        raise RuntimeError(
            "PetEVAL: HF_TOKEN not set. Set HF_TOKEN=hf_xxxx and accept dataset conditions at "
            "https://huggingface.co/datasets/SAVSNET/PetEVAL"
        )

    from datasets import load_dataset

    ds = load_dataset("SAVSNET/PetEVAL", token=hf_token, revision=revision)
    splits = list(ds.keys())
    print(f"  PetEVAL splits: {splits}")

    frames = []
    for split in splits:
        df_split = ds[split].to_pandas()
        frames.append(df_split)
    raw = pd.concat(frames, ignore_index=True)

    print(f"  PetEVAL columns: {list(raw.columns)}")
    print(f"  PetEVAL total rows: {len(raw)}")

    # Detect text column
    text_col = None
    for candidate in ["text", "clinical_notes", "narrative", "consultation_text", "note"]:
        if candidate in raw.columns:
            text_col = candidate
            break

    # Detect label column (Main Presenting Complaint preferred)
    label_col = None
    for candidate in [
        "main_presenting_complaint",
        "mpc",
        "presenting_complaint",
        "syndromic_label",
        "label",
        "condition",
        "icd_label",
    ]:
        if candidate in raw.columns:
            label_col = candidate
            break

    if text_col is None or label_col is None:
        raise ValueError(f"PetEVAL: couldn't find text/label columns in {list(raw.columns)}")

    rows = []
    for _, r in raw.iterrows():
        label = str(r[label_col]).strip()
        if label in _PETEVALSKIP_COMPLAINTS or not label:
            continue
        text = str(r[text_col]).strip()
        if len(text) < 10:
            continue

        # Map PetEVAL labels via label_map.json (Gastrointestinal → Digestive Issues etc.)
        # If not in map, keep as-is and let train.py's min-samples filter handle it
        rows.append({"text": text, "condition": label, "record_type": "PetEVAL"})

    df = pd.DataFrame(rows)
    print(f"  Loaded {len(df)} usable rows from PetEVAL")
    return df


# ---------------------------------------------------------------------------
# Main merge logic
# ---------------------------------------------------------------------------


def _load_synthetic(synthetic_path: str) -> pd.DataFrame:
    """Load ALL synthetic files in the data directory, not just one.

    Picks up the given path PLUS any sibling ``synthetic*.parquet`` / ``synthetic*.csv``
    (e.g. synthetic_data.parquet AND synthetic_owner.parquet), so newly generated
    files are merged automatically instead of being silently ignored.
    """
    base = Path(synthetic_path)
    data_dir = base.parent if base.parent != Path("") else Path(".")

    candidates: list[Path] = []
    if base.exists():
        candidates.append(base)
    for pattern in ("synthetic*.parquet", "synthetic*.csv"):
        candidates.extend(sorted(data_dir.glob(pattern)))

    # De-duplicate paths while preserving order.
    seen: set[Path] = set()
    files: list[Path] = []
    for candidate in candidates:
        if candidate not in seen:
            seen.add(candidate)
            files.append(candidate)

    if not files:
        print(f"  [skip] No synthetic files found in {data_dir}/ (synthetic*.parquet|csv)")
        print("         Run first: python -m ml_pipeline.generate_synthetic")
        return pd.DataFrame()

    frames = []
    for path in files:
        df = pd.read_csv(path) if path.suffix.lower() == ".csv" else pd.read_parquet(path)
        df = df[["text", "condition", "record_type"]].copy()
        print(f"  Loaded {len(df)} synthetic rows from {path.name}")
        frames.append(df)

    merged = pd.concat(frames, ignore_index=True).drop_duplicates(subset=["text", "condition"])
    print(f"  Total synthetic rows (deduped): {len(merged)}")
    return merged


def fetch_and_merge(
    local_path: str = "data/merged_pet_dataset.parquet",
    synthetic_path: str = "data/synthetic_data.parquet",
    label_map_path: str = "data/label_map.json",
    output_path: str = "data/merged_augmented.parquet",
    skip_vetpetcare: bool = False,
    skip_synthetic: bool = False,
    skip_petevalopen: bool = False,
    min_text_length: int = 15,
    vetpetcare_revision: str | None = None,
    peteval_revision: str | None = None,
    require_sources: frozenset[str] = frozenset(),
) -> None:
    """`require_sources` names sources (from {"local", "vetpetcare", "synthetic",
    "peteval"}) that MUST load successfully — a STRICT source that fails aborts
    the build (`DatasetSourceError`) instead of being silently skipped. Every
    source's outcome (rows loaded, pinned revision, failure reason) is recorded
    in a build manifest written alongside the output parquet."""
    label_map = _load_label_map(label_map_path)
    frames: list[pd.DataFrame] = []
    source_results: list[SourceResult] = []

    def mode_for(name: str) -> SourceMode:
        return SourceMode.STRICT if name in require_sources else SourceMode.BEST_EFFORT

    # 1. Existing local dataset
    print("\n[1/4] Loading local dataset...")

    def _local_loader() -> pd.DataFrame:
        df = _load_local(local_path)
        if df.empty:
            return df
        df["condition"] = df["condition"].map(
            lambda c: label_map.get(str(c).strip(), str(c).strip())
        )
        return df

    local_df, local_result = load_source("local", mode_for("local"), _local_loader)
    source_results.append(local_result)
    if local_result.loaded:
        frames.append(local_df)
    elif local_result.error:
        print(f"  [skip] local dataset failed: {local_result.error}")

    # 2. VetPetCare (free, no account needed)
    if not skip_vetpetcare:
        print("\n[2/4] Fetching VetPetCare (free)...")
        vetpetcare_df, vetpetcare_result = load_source(
            "vetpetcare",
            mode_for("vetpetcare"),
            lambda: _load_vetpetcare(label_map, revision=vetpetcare_revision),
            revision=vetpetcare_revision,
        )
        source_results.append(vetpetcare_result)
        if vetpetcare_result.loaded:
            frames.append(vetpetcare_df)
        elif vetpetcare_result.error:
            print(f"  [skip] VetPetCare failed: {vetpetcare_result.error}")
    else:
        print("\n[2/4] VetPetCare: skipped (--skip-vetpetcare)")

    # 3. Synthetic data from Gemini (free — uses your existing API key)
    if not skip_synthetic:
        print("\n[3/4] Loading synthetic data (Gemini-generated)...")
        synthetic_df, synthetic_result = load_source(
            "synthetic", mode_for("synthetic"), lambda: _load_synthetic(synthetic_path)
        )
        source_results.append(synthetic_result)
        if synthetic_result.loaded:
            frames.append(synthetic_df)
        elif synthetic_result.error:
            print(f"  [skip] synthetic data failed: {synthetic_result.error}")
    else:
        print("\n[3/4] Synthetic data: skipped (--skip-synthetic)")

    # 4. PetEVAL (gated — optional)
    if not skip_petevalopen:
        print("\n[4/4] Fetching PetEVAL (gated — needs HF_TOKEN)...")

        def _peteval_loader() -> pd.DataFrame:
            df = _load_petevalopen(revision=peteval_revision)
            if df.empty:
                return df
            df["condition"] = df["condition"].map(
                lambda c: label_map.get(str(c).strip(), str(c).strip())
            )
            return df

        petevalopen_df, peteval_result = load_source(
            "peteval", mode_for("peteval"), _peteval_loader, revision=peteval_revision
        )
        source_results.append(peteval_result)
        if peteval_result.loaded:
            frames.append(petevalopen_df)
        elif peteval_result.error:
            print(f"  [skip] PetEVAL failed: {peteval_result.error}")
    else:
        print("\n[4/4] PetEVAL: skipped (--skip-petevalopen)")

    if not frames:
        raise RuntimeError("No data loaded — nothing to merge.")

    # Merge + clean
    merged = pd.concat(frames, ignore_index=True)
    merged["text"] = merged["text"].astype(str).str.replace(r"\s+", " ", regex=True).str.strip()
    merged["condition"] = merged["condition"].astype(str).str.strip()
    merged = merged[merged["text"].str.len() >= min_text_length]
    merged = merged.dropna(subset=["text", "condition"])
    merged = merged[merged["condition"] != "nan"]
    merged["record_type"] = merged["record_type"].fillna("External Dataset")

    # Deduplicate on text+condition
    before = len(merged)
    merged = merged.drop_duplicates(subset=["text", "condition"])
    print(f"\nDeduplication removed {before - len(merged)} rows")

    # Summary
    print(f"\n{'='*50}")
    print(f"Final merged dataset: {len(merged)} rows, {merged['condition'].nunique()} classes")
    print("\nClass distribution:")
    print(merged["condition"].value_counts().to_string())
    print("\nSource breakdown:")
    print(merged["record_type"].value_counts().to_string())

    # Save
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    merged.to_parquet(output, index=False)
    print(f"\nSaved to: {output}")

    # Build manifest: what sources actually contributed to this build, at what
    # pinned revision — the traceability record required by
    # "Canonical and traceable dataset builds" (specs/reproducible-ml-lifecycle).
    manifest = {
        "generated_at": datetime.now(UTC).isoformat(),
        "output": str(output),
        "output_rows": len(merged),
        "min_text_length": min_text_length,
        "label_map_path": label_map_path,
        "sources": [r.as_dict() for r in source_results],
    }
    manifest_path = output.with_name(output.name + ".manifest.json")
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"Wrote build manifest to: {manifest_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch external vet datasets and merge into augmented training file.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--local-path",
        default="data/merged_pet_dataset.parquet",
        help="Existing local dataset to include.",
    )
    parser.add_argument(
        "--synthetic-path",
        default="data/synthetic_data.parquet",
        help="Synthetic data file from generate_synthetic.py.",
    )
    parser.add_argument(
        "--label-map", default="data/label_map.json", help="Label consolidation map JSON."
    )
    parser.add_argument(
        "--output",
        default="data/merged_augmented.parquet",
        help="Output path for the augmented dataset.",
    )
    parser.add_argument("--skip-vetpetcare", action="store_true", help="Skip fetching VetPetCare.")
    parser.add_argument(
        "--skip-synthetic", action="store_true", help="Skip loading synthetic data."
    )
    parser.add_argument(
        "--skip-petevalopen", action="store_true", help="Skip fetching PetEVAL (gated)."
    )
    parser.add_argument(
        "--min-text-length", type=int, default=15, help="Drop rows with text shorter than this."
    )
    parser.add_argument(
        "--vetpetcare-revision",
        default=None,
        help="Pin the VetPetCare HF dataset revision (commit/tag) for traceability.",
    )
    parser.add_argument(
        "--peteval-revision",
        default=None,
        help="Pin the PetEVAL HF dataset revision (commit/tag) for traceability.",
    )
    parser.add_argument(
        "--require-source",
        action="append",
        default=[],
        choices=["local", "vetpetcare", "synthetic", "peteval"],
        help="Source that MUST load successfully — repeat to require several. "
        "A failure aborts the build instead of being skipped.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    try:
        fetch_and_merge(
            local_path=args.local_path,
            synthetic_path=args.synthetic_path,
            label_map_path=args.label_map,
            output_path=args.output,
            skip_vetpetcare=args.skip_vetpetcare,
            skip_synthetic=args.skip_synthetic,
            skip_petevalopen=args.skip_petevalopen,
            min_text_length=args.min_text_length,
            vetpetcare_revision=args.vetpetcare_revision,
            peteval_revision=args.peteval_revision,
            require_sources=frozenset(args.require_source),
        )
    except DatasetSourceError as exc:
        raise SystemExit(f"Build aborted: {exc}") from exc
